services:
    Thumbor\Url\BuilderFactory:
        class: 'Thumbor\Url\BuilderFactory'
        arguments:
            - '%phumbor.server.url%'
            - '%phumbor.secret%'

    Webfactory\Bundle\PhumborBundle\Transformer\BaseTransformer:
        class: 'Webfactory\Bundle\PhumborBundle\Transformer\BaseTransformer'
        arguments:
            - '@Thumbor\Url\BuilderFactory'
            - '%phumbor.transformations%'

    Webfactory\Bundle\PhumborBundle\Twig\PhumborExtension:
        class: 'Webfactory\Bundle\PhumborBundle\Twig\PhumborExtension'
        arguments:
            - '@Webfactory\Bundle\PhumborBundle\Transformer\BaseTransformer'
        tags:
            - { name: twig.extension }
